// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwGoG5s3bg-aXGjqW0jruwQtuaU7Z4ahU',
    appId: '1:879511527878:web:62d383b659b51e20d352c7',
    messagingSenderId: '879511527878',
    projectId: 'burger-f00d',
    authDomain: 'burger-f00d.firebaseapp.com',
    storageBucket: 'burger-f00d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvXLzm13-gT9gNF2L7cE3jLe50Y197Kg',
    appId: '1:879511527878:android:11be24e12cbc6da3d352c7',
    messagingSenderId: '879511527878',
    projectId: 'burger-f00d',
    storageBucket: 'burger-f00d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hQKx-beu3J4ynxUPGHAX_Zy29-f4Gno',
    appId: '1:879511527878:ios:170ec22760008a47d352c7',
    messagingSenderId: '879511527878',
    projectId: 'burger-f00d',
    storageBucket: 'burger-f00d.appspot.com',
    iosBundleId: 'com.example.burgerFood',
  );
}
